CREATE DATABASE IF NOT EXISTS maBaseDeDonnees;
USE maBaseDeDonnees;

DROP TABLE IF EXISTS Utilisateurs;
CREATE TABLE Utilisateurs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Nom VARCHAR(50) NOT NULL,
    Prenom VARCHAR(50) NOT NULL,
    DateNaissance DATE, 
    Pseudonyme VARCHAR(50) NOT NULL UNIQUE, 
    Email VARCHAR(100) NOT NULL UNIQUE, 
    MotDePasse VARCHAR(255) NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
