CREATE TABLE Utilisateurs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Nom VARCHAR(50) NOT NULL,
    Prenom VARCHAR(50) NOT NULL,
    DateNaissance DATE,
    Pseudonyme VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    MotDePasse VARCHAR(255) NOT NULL
);

