SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE Utilisateurs;
TRUNCATE TABLE Gouts;
TRUNCATE TABLE LikeList;
TRUNCATE TABLE Messages;
TRUNCATE TABLE Report;
TRUNCATE TABLE Contact;

SET FOREIGN_KEY_CHECKS = 1;
